[build]
target = "x86_64-unknown-none"
rustflags = [
  "-C", "panic=abort",
  "-Z", "panic_abort_tests"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = []