[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
limine = "0.5.0"
volatile = "0.2.6"
x86_64 = "0.15.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "blog_os"
test = false
bench = false
